color: null
fieldLayouts:
  e42e7c97-61b5-4a85-8841-a8efd8a91140:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e6bcf059-6d0b-4193-88d8-147c58fcb164
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b3b4258e-fa53-4033-a49b-c8cbf7929fea # hero title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0a00da5-e3b4-4ed1-ae5c-33ab5f196754
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 259788c2-1c6c-436e-b741-080357ffdc18 # hero image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 17948af1-96ec-44d9-84a8-5225aaae9d2f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 324c43e9-bd03-409d-ab4a-61bb60ebc873
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e0b9a4e6-4aa6-476b-aec5-22adb5227691 # nu in de tuin
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 42d5321d-dc82-4702-bf0d-1e1dbb5c2c86
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 96b220b2-47fe-4d09-97f9-e178f2806150 # blog post
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5a9ce584-0d0c-4acf-93d0-fea85e999933
            userCondition: null
            warning: null
            width: 100
        name: blogs
        uid: 77594269-959a-4ee6-93b5-044466df1361
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: dc6877fa-1362-424e-a45f-fb8020437964 # Waarom title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b4953448-b312-43ba-881d-fe7dc4c4312b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b5747fbb-3ed3-4bc4-aace-dec17138090d # Waarom
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b37b845b-6aad-44bc-8a97-febaac08109a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 29e39072-19d9-4f1d-9cd5-ff0630730db5 # waarom Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43d30d45-f3cd-4342-9ed6-22484fae9a88
            userCondition: null
            warning: null
            width: 100
        name: 'waarom tuinrangers'
        uid: 923f95e1-0930-43e2-92a4-3f2d1506c551
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: de7d968b-52ec-4bd0-9e05-44c1c7199710 # zelf doen title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef1b3314-68d9-4078-9043-c1ee956397a0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0ef1347f-b496-4218-a672-4eaf6ff064d8 # zelf doen description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 92aa475d-bb4d-4dab-ac35-899c2dfe4f23
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2834852d-83d7-48d9-a63a-a4624fd9f98a # zelf doen image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec4468aa-82ad-4411-abca-5a81cf49f2c0
            userCondition: null
            warning: null
            width: 100
        name: 'zelf doen'
        uid: 9ec88a2d-fcac-4cb4-a5ae-92dee6cce5a0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9e33d045-0f1d-485a-b635-a143c24f1407 # nav bottom
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b2781437-e67c-4860-ab8c-d9befddb2cae
            userCondition: null
            warning: null
            width: 100
        name: header
        uid: 36b5bc76-09bc-4c08-94a9-92176b593604
        userCondition: null
handle: entry
hasTitleField: true
icon: ''
name: entry
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
