color: null
fieldLayouts:
  fad5e934-e453-4352-8b74-94befaafce01:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a16bbdf6-7c69-4906-b295-5a3b7a51c6d2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 58e4b376-9d47-4e7e-99d7-ecf63e7ba7bf # blog title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da076627-2e87-4558-8db0-33d97d15a907
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 260ac49d-4dcc-41cb-96af-9738aa642bcd
        userCondition: null
handle: story
hasTitleField: true
icon: ''
name: story
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
