altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  7c773789-cc17-4626-b7ce-3ef599e976f9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 3f673f49-bf74-4008-bbbe-94bf9c038719
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8937e953-e6b0-4c4e-9979-96a96ec65cec
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b82739fe-d9e6-493b-9133-ee058fa287fc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8fee7be7-1df9-4273-9213-6af36524cf5e
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 669f302e-b745-4756-bca5-f5709bca3863
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 149f6671-f5db-427a-b2f7-8dc501154227
        userCondition: null
fs: uploads2
handle: uploads
name: uploads
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
