columnSuffix: null
handle: blogs
instructions: null
name: 'blog post'
searchable: false
settings:
  createButtonLabel: null
  entryTypes:
    - 4f6f2354-fd48-4a5f-bd2e-7e439637d8d9 # blog post
  includeTableView: false
  maxEntries: 3
  minEntries: 1
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
