columnSuffix: null
handle: navTop
instructions: null
name: 'nav top'
searchable: false
settings:
  createButtonLabel: null
  entryTypes:
    - e680c0b8-a5dc-492e-9509-994ef1210f38 # links top
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
