columnSuffix: null
handle: sponsorLogos
instructions: null
name: 'sponsor logos'
searchable: false
settings:
  createButtonLabel: null
  entryTypes:
    - 81f9d9c0-3cdf-47e6-a09b-9e6df9a4e93d # sponsor logo
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
