columnSuffix: null
handle: zelfDoenDescription
instructions: null
name: 'zelf doen description'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 25
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
