fieldLayouts:
  8f288bc5-a94b-431d-bcb6-8ceadbede366:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7190a5f6-235e-4f71-b883-56c33f206545 # copyright
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 928c4c79-5f88-44dd-8cce-caee61277323
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 67dabfa2-22cb-40f8-980a-97412442e75c # nav voorwaarden
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2f206c3-1177-4793-aa2b-f68227f8acbf
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 973b97e1-4f77-4c01-b8b4-28c65471dedd
        userCondition: null
handle: footerDrie
name: 'footer drie'
sortOrder: 4
